
CONTROLLER="$PWD/hbgp"
AGENT="$PWD/hbgp.event"
HBGP="$PWD/hbgp"

KAKAPO="/home/nic/src/kakapo/core/kakapo"
KAKAPOCMD="kakapo 7.0.0.1,7.0.0.2,65000 7.0.0.5,7.0.0.6,65000"
KAKAPOENV="SENDFILENAME=${PWD}/updates.raw TIMEOUT=1000 MODE=FILE"
#ENV="SENDFILENAME=/home/nic/src/hBGP.master/MRT/raw/66234.raw TIMEOUT=1000 REPEAT=1 MODE=FILE"
#ENV="SENDFILENAME=updates.raw TIMEOUT=100 REPEAT=3 MODE=FILE"
# ENV="TIMEOUT=60 REPEAT=1 TABLESIZE=160000 GROUPSIZE=5 BLOCKSIZE=1 MODE=SINGLE"
#ENV="BLOCKSIZE=1 MODE=SINGLERATE"

EXALOCAL=/home/nic/src/exa-simple
EXABASE=/home/nic/src/exabgp
EXA=$EXABASE/sbin/exabgp

